# -*- coding: utf-8 -*-
"""scoregen.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15J3l0y2ZEitkBG4UzavDUoye0AkI0jwH
"""

import pandas as pd
import re

# Logic to clean the data manually
cleaned_data = []
current_id = None
current_text = []

# Regex to find the "Anchor" (Start of a new row)
# Looks for: Start of line (^), Digits (\d+), followed by a comma (,)
new_row_pattern = re.compile(r'^(\d+),(.*)')

print("Starting manual parsing... this handles broken newlines and commas.")

with open('/content/drive/MyDrive/Steam/reviews only.csv', 'r', encoding='utf-8', errors='replace') as f:
    for i, line in enumerate(f):
        line = line.strip() # Remove trailing newline characters

        # Check if this line is the start of a new row (ID, Text...)
        match = new_row_pattern.match(line)

        if match:
            # 1. SAVE PREVIOUS: If we were building a row, save it now
            if current_id is not None:
                full_review = " ".join(current_text) # Merge multi-line text
                cleaned_data.append({'recommendationid': current_id, 'review_text': full_review})

            # 2. START NEW: Start the new row
            current_id = match.group(1)      # The ID (e.g., 10000000)
            initial_text = match.group(2)    # The start of the review
            current_text = [initial_text]    # Start the text buffer

        else:
            # 3. APPEND: This line is a continuation of the previous review
            # (Only if we have a valid ID started)
            if current_id is not None:
                current_text.append(line)

    # Don't forget to save the very last row!
    if current_id is not None:
        full_review = " ".join(current_text)
        cleaned_data.append({'recommendationid': current_id, 'review_text': full_review})

# Convert to DataFrame
df_clean = pd.DataFrame(cleaned_data)

print(f"Successfully reconstructed {len(df_clean)} rows.")

print(df_clean.head(10))

demo = df_clean.head(100).copy()

import pandas as pd
from transformers import pipeline
from transformers.pipelines.pt_utils import KeyDataset
import torch
from tqdm.auto import tqdm
import os
import time

# --- CONFIGURATION ---
drive_path = '/content/drive/MyDrive/Steam/reviews_scored_partial.csv'
batch_save_size = 50000   # Save to Drive every 50k
status_update_interval = 10000 # Print status every 10k

# ==========================================
# CONFIGURATION
# ==========================================
drive_path = '/content/drive/MyDrive/Steam/reviews_scored_final.csv'
batch_save_size = 50000
status_interval = 10000

# ==========================================
# 1. RESET BAD FILE
# ==========================================
if os.path.exists(drive_path):
    print(f"⚠️ Deleting bad file: {drive_path}")
    os.remove(drive_path)

# Create fresh file
pd.DataFrame(columns=['recommendationid', 'numeric_score', 'category']).to_csv(drive_path, index=False)
print("✅ Created fresh output file.")

# Check if df_clean exists (from previous cell)
if 'df_clean' not in locals():
    raise ValueError("df_clean is missing! Please run the 'Data Cleaning' cell again.")

# ==========================================
# 2. SETUP MODEL
# ==========================================
device = 0 if torch.cuda.is_available() else -1
print(f"Using Device: {'GPU 🚀' if device == 0 else 'CPU 🐢'}")

sentiment_pipeline = pipeline(
    task='sentiment-analysis',
    model='nlptown/bert-base-multilingual-uncased-sentiment',
    device=device,
    truncation=True,
    max_length=512,
    batch_size=32 # Optimized for T4
)

star_map = {1: 'Worse', 2: 'Bad', 3: 'Neutral', 4: 'Good', 5: 'Best'}

# ==========================================
# 3. CORRECT PROCESSING LOOP
# ==========================================
print(f"Processing {len(df_clean)} rows...")

# Initialize data stream
data_stream = KeyDataset(df_clean.to_dict('records'), "review_text")

current_batch = []
start_time = time.time()

print("-" * 50)

# --- THE FIX IS HERE ---
# We iterate over the PIPELINE result, not the data_stream itself
pipeline_iterator = sentiment_pipeline(data_stream, batch_size=32)

for i, out in tqdm(enumerate(pipeline_iterator), total=len(df_clean)):

    # DEBUG: Print first row to prove it works this time
    if i == 0:
        print(f"\n[DEBUG CHECK] Row 0 Output: {out}")
        # Should be: {'label': '1 star', 'score': ...}

    try:
        # Handle Output
        if isinstance(out, list):
            result = out[0]
        else:
            result = out

        star = int(result['label'].split()[0])
        category = star_map.get(star, 'Unknown')

    except Exception as e:
        if i < 5: print(f"❌ Error on row {i}: {e}")
        star = -1
        category = "Error"

    # Save Result
    original_idx = df_clean.index[i]
    current_batch.append({
        'recommendationid': df_clean.at[original_idx, 'recommendationid'],
        'numeric_score': star,
        'category': category
    })

    # STATUS & SAVE
    if (i + 1) % status_interval == 0:
        elapsed = time.time() - start_time
        print(f"Status: {i + 1} rows done. (Last 10k took: {elapsed:.2f}s)")
        start_time = time.time()

    if (i + 1) % batch_save_size == 0:
        pd.DataFrame(current_batch).to_csv(drive_path, mode='a', header=False, index=False)
        print(f"  💾 SAVED to Drive: {i + 1} rows safe.")
        current_batch = []

# Final Save
if current_batch:
    pd.DataFrame(current_batch).to_csv(drive_path, mode='a', header=False, index=False)
    print("  💾 Final Batch Saved.")

print(f"\n✅ COMPLETE! File saved at: {drive_path}")

from transformers import AutoTokenizer, AutoModelForSequenceClassification

model_name = "nlptown/bert-base-multilingual-uncased-sentiment"
output_dir = "./sentiment_model_local"

# 1. Download and Save locally
print("Downloading model...")
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSequenceClassification.from_pretrained(model_name)

tokenizer.save_pretrained(output_dir)
model.save_pretrained(output_dir)

print(f"Model saved to {output_dir}")

"""
# 2. Upload to S3 (using AWS CLI or Python)
# You need to upload the WHOLE folder (config.json, pytorch_model.bin, etc.)
# Example using boto3:
import boto3
import os

s3 = boto3.client('s3')
bucket_name = 'your-s3-bucket-name'
s3_prefix = 'models/bert-sentiment/'

for filename in os.listdir(output_dir):
    local_path = os.path.join(output_dir, filename)
    s3_path = os.path.join(s3_prefix, filename)
    print(f"Uploading {filename} to s3://{bucket_name}/{s3_path}")
    s3.upload_file(local_path, bucket_name, s3_path)

"""