# -*- coding: utf-8 -*-
"""Game Search

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pwFkcJBgek4VzkGEqdSRxndFxrf7gv5H
"""

!pip install -q umap-learn sentence-transformers

from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
# Core imports
import pandas as pd
import numpy as np
import json
from pathlib import Path
import warnings
warnings.filterwarnings('ignore')

# Visualization
import matplotlib.pyplot as plt
import seaborn as sns
from matplotlib.patches import Patch

# ML/NLP
from sklearn.metrics.pairwise import cosine_similarity
import umap
from sentence_transformers import SentenceTransformer

# Plotting configuration
plt.style.use('seaborn-v0_8-darkgrid')
sns.set_palette("husl")
# %matplotlib inline

print("✅ All packages loaded successfully")

DATA_DIR = Path(r"/content/drive/MyDrive/Steam/steam-dataset-2025")
print(f"Data directory: {DATA_DIR}")
print(f"Directory exists: {DATA_DIR.exists()}")

# Commented out IPython magic to ensure Python compatibility.
!git lfs install

!git clone https://github.com/vintagedon/steam-dataset-2025.git

# %cd steam-dataset-2025

!git lfs pull

ls -lh /content/steam-dataset-2025/steam-dataset-2025-v1/notebook-data/02-semantic-game-discovery

!find /content/ -name "02_embeddings_vectors.npy"

!cp /content/drive/MyDrive/Steam/steam-dataset-2025/steam-dataset-2025-v1/notebook-data/02-semantic-game-discovery/02_embeddings_vectors.npy \
/content/steam-dataset-2025/steam-dataset-2025-v1/notebook-data/02-semantic-game-discovery/

from pathlib import Path

DATA_DIR = Path(
    "/content/steam-dataset-2025/steam-dataset-2025-v1/notebook-data/02-semantic-game-discovery"
)

def validate_semantic_dataset(df_meta, df_appids, embeddings, df_genres):
    # LFS pointer detection
    if list(df_meta.columns) == ["version https://git-lfs.github.com/spec/v1"]:
        raise RuntimeError("LFS POINTER FILE DETECTED: metadata")

    # Row alignment
    if not (len(df_meta) == embeddings.shape[0] == len(df_appids)):
        raise RuntimeError("DATA MISALIGNMENT between metadata, embeddings, and appids")

    # Required columns
    required_meta = {"appid", "short_description", "primary_genre"}
    required_genres = {"appid", "genre"}

    if not required_meta.issubset(df_meta.columns):
        raise RuntimeError("Metadata schema invalid")

    if not required_genres.issubset(df_genres.columns):
        raise RuntimeError("Genre schema invalid")

    # Embedding sanity
    if embeddings.ndim != 2:
        raise RuntimeError("Embeddings not 2D")

    print("✅ Semantic dataset validation passed")

# Load metadata CSV
df_metadata = pd.read_csv(DATA_DIR / '01_game_embeddings_sample.csv')

# Load embedding vectors (NumPy format)
embeddings = np.load(DATA_DIR / '02_embeddings_vectors.npy')

# Load appid mapping
df_appids = pd.read_csv(DATA_DIR / '02_embeddings_appids.csv')

# Load genre representatives
df_genres = pd.read_csv(DATA_DIR / '02_genre_representatives.csv')

# Load pre-computed semantic search examples
with open(DATA_DIR / '02_semantic_search_examples.json', 'r') as f:
    search_examples = json.load(f)

print("✅ All data files loaded successfully")

# Validation: Verify data alignment
print("=" * 60)
print("DATA VALIDATION")
print("=" * 60)

print(f"\nMetadata rows: {len(df_metadata):,}")
print(f"Embedding vectors: {embeddings.shape[0]:,}")
print(f"AppID mappings: {len(df_appids):,}")
print(f"Alignment check: {'✅ PASS' if len(df_metadata) == embeddings.shape[0] == len(df_appids) else '❌ FAIL'}")

print(f"\nEmbedding dimensions: {embeddings.shape[1]}")
print(f"Vector data type: {embeddings.dtype}")
print(f"Memory usage: {embeddings.nbytes / 1024 / 1024:.1f} MB")

print(f"\nVector normalization check:")
norms = np.linalg.norm(embeddings, axis=1)
print(f"  Mean L2 norm: {norms.mean():.6f}")
print(f"  Std deviation: {norms.std():.6f}")
print(f"  All normalized: {'✅ YES' if np.allclose(norms, 1.0, atol=0.001) else '❌ NO'}")

print(f"\nGenre representatives: {len(df_genres):,} games across {df_genres['genre'].nunique()} genres")
print(f"Semantic search examples: {len(search_examples)} pre-computed queries")

print(df_metadata.columns)
print(df_appids.columns)
print(df_genres.columns)

# OPTIONAL: Enable live semantic search (requires model download)
# Uncomment to activate:

# Load BGE-M3 model
print("Loading BGE-M3 model (one-time download ~2.3GB)...")
model = SentenceTransformer('BAAI/bge-m3')
print("✅ Model loaded")


# def semantic_search(query_text, top_k=10):
#     """
#     Perform semantic search on game descriptions.

#     Args:
#         query_text (str): Natural language search query
#         top_k (int): Number of results to return

#     Returns:
#         DataFrame with top matching games and similarity scores
#     """
#     # Generate query embedding
#     query_embedding = model.encode(query_text)

#     # Calculate cosine similarity with all game embeddings
#     similarities = cosine_similarity([query_embedding], embeddings)[0]

#     # Get top K indices
#     top_indices = similarities.argsort()[-top_k:][::-1]

#     # Build results dataframe
#     results = df_metadata.iloc[top_indices][['appid', 'name', 'short_description', 'primary_genre', 'price_usd']].copy()
#     results['similarity_score'] = similarities[top_indices]

#     return results



print("💡 Live search function defined (commented out by default)")
print("   Uncomment the code below to enable interactive queries")

# Example of using the semantic_search function
query = "games with relaxing content"
results = semantic_search(query, top_k=5)

print(f"\nTop 5 games for query: '{query}'")
print("=" * (len(query) + 26))
print(results.to_string(index=False))

import os
import pandas as pd
import numpy as np
from pathlib import Path
from sklearn.metrics.pairwise import cosine_similarity
from sentence_transformers import SentenceTransformer

# ==========================================
# 1. SETUP & LOAD VECTOR DATA
# ==========================================
print("⬇️ Loading Search Index...")
base_dir = Path("/content/steam-dataset-2025/steam-dataset-2025-v1/notebook-data")

# Load Vectors
vec_path = list(base_dir.rglob("02_embeddings_vectors.npy"))[0]
game_embeddings = np.load(vec_path)

# Load Metadata
meta_path = list(base_dir.rglob("01_game_embeddings_sample.csv"))[0]
df_metadata = pd.read_csv(meta_path)
df_metadata['appid'] = df_metadata['appid'].astype(str)

# Load ID Index
id_path = list(base_dir.rglob("02_embeddings_appids.csv"))[0]
df_appids = pd.read_csv(id_path)
df_appids['appid'] = df_appids['appid'].astype(str)

# Create Base Search Table
df_search_index = pd.merge(df_appids, df_metadata, on='appid', how='left')
df_search_index['name'] = df_search_index['name'].fillna("Unknown Game")
print(f"✅ Search Index Ready: {len(df_search_index)} games.")

# ==========================================
# 2. LOAD YOUR MEDIA FILES (Drive Paths)
# ==========================================
print("\n⏳ Loading New Media Files...")

# Define Paths
master_file = "/content/drive/MyDrive/Steam/appid_recommendationid_numeric_score_header_image_background.csv"
screens_file = "/content/drive/MyDrive/Steam/appid_screenshots.csv"

# --- A. PROCESS MASTER FILE (Scores + Header/Background) ---
if os.path.exists(master_file):
    print("   reading master file...")
    # FIX: on_bad_lines='skip' prevents the crash from bad rows
    df_master = pd.read_csv(master_file, on_bad_lines='skip')
    df_master['appid'] = df_master['appid'].astype(str).str.replace(".0", "", regex=False)

    # 1. Extract Scores
    df_scores = df_master.groupby('appid')['numeric_score'].mean().reset_index()
    df_scores.rename(columns={'numeric_score': 'avg_sentiment_score'}, inplace=True)

    # 2. Extract Images
    df_images = df_master[['appid', 'header_image', 'background']].drop_duplicates(subset=['appid'])

    print(f"   ✅ Loaded Scores & Images for {len(df_images)} games.")
else:
    print(f"   ❌ Master File Not Found: {master_file}")
    df_scores = pd.DataFrame()
    df_images = pd.DataFrame()

# --- B. PROCESS SCREENSHOTS FILE ---
if os.path.exists(screens_file):
    print("   reading screenshots file...")
    df_screens_raw = pd.read_csv(screens_file, on_bad_lines='skip') # Safety first
    df_screens_raw['appid'] = df_screens_raw['appid'].astype(str).str.replace(".0", "", regex=False)

    # Group into Lists: AppID 123 -> [url1, url2...]
    df_screenshots = df_screens_raw.groupby('appid')['screenshot_url'].apply(list).reset_index()
    df_screenshots.rename(columns={'screenshot_url': 'screenshots'}, inplace=True)

    print(f"   ✅ Loaded Screenshots for {len(df_screenshots)} games.")
else:
    print(f"   ❌ Screenshots File Not Found: {screens_file}")
    df_screenshots = pd.DataFrame()

# ==========================================
# 3. SEARCH ENGINE (With Steam Links!)
# ==========================================
print("\n🚀 Initializing Search Engine...")
model = SentenceTransformer("BAAI/bge-m3")

def search_games(query, top_k=10):
    print(f"\n🔎 Searching for: '{query}'")

    # 1. Vector Search
    query_vec = model.encode(query).reshape(1, -1)
    sims = cosine_similarity(query_vec, game_embeddings)[0]

    # 2. Get Top Matches
    top_indices = sims.argsort()[-top_k:][::-1]
    results = df_search_index.iloc[top_indices].copy()
    results['similarity_score'] = sims[top_indices]

    # 3. Create Steam Link (NEW!)
    # We build the URL dynamically using the AppID
    results['steam_url'] = "https://store.steampowered.com/app/" + results['appid'] + "/"

    # 4. Attach SCORES
    if not df_scores.empty:
        results = pd.merge(results, df_scores, on='appid', how='left')
        results['avg_sentiment_score'] = results['avg_sentiment_score'].fillna(0).round(2)
    else:
        results['avg_sentiment_score'] = 0.0

    # 5. Attach IMAGES
    if not df_images.empty:
        results = pd.merge(results, df_images, on='appid', how='left')

    # 6. Attach SCREENSHOTS
    if not df_screenshots.empty:
        results = pd.merge(results, df_screenshots, on='appid', how='left')

    # 7. Final Columns
    cols = [
        'name',
        'steam_url',         # <--- Added right here!
        'similarity_score',
        'avg_sentiment_score',
        'primary_genre',
        'price_usd',
        'currency',
        'header_image',
        'background',
        'screenshots',
        'short_description'
    ]

    return results[cols].fillna("Missing")

# ==========================================
# 4. TEST IT
# ==========================================
display(search_games("games like GTA 5"))